prompts = {
    "Gratitude": [
        "What are three things you're grateful for in your life right now, and why?",
        "Reflect on a challenge you faced recently. What positives or lessons came from it that you're grateful for?",
        "Write about a person who has deeply impacted your life in a positive way, and express your gratitude towards them.",
        "List five things in nature that you're grateful for and why they bring you joy.",
        "How has practicing gratitude changed your perspective on life and your overall well-being?",
        "Write about a small moment today that you're grateful for, even if it seemed insignificant.",
        "What are three things about yourself that you're grateful for?",
        "Reflect on a past experience that you initially perceived as negative but now realize had positive aspects. What were they?",
        "Write a letter of gratitude to someone who has supported you during a difficult time.",
        "What are some simple pleasures in your life that you're grateful for?",
        "Describe a recent act of kindness you received and how it made you feel grateful.",
        "Reflect on the opportunities you have in your life that others may not. How does this make you feel grateful?",
        "What are three aspects of your health and well-being that you're grateful for?",
        "Write about a specific skill or talent you possess that you're grateful for.",
        "List three things about your home that you're grateful for.",
        "Reflect on a valuable lesson you learned from a mistake or failure. How has this experience made you more grateful?",
        "What are some ways you can express gratitude towards yourself today?",
        "Write about a memory from your childhood that you're grateful for.",
        "Describe a friend or family member who has supported you unconditionally, and express your gratitude towards them.",
        "List three things about your job or career that you're grateful for."
    ],
    "Morning": [
        "What are three things you're looking forward to today?",
        "Set an intention for the day ahead and write about why it's important to you.",
        "Reflect on one thing you're grateful for as you start your day.",
        "Write down three things you love about yourself to boost your confidence for the day.",
        "Describe one small action you can take today to prioritize your well-being.",
        "List three tasks you want to accomplish today, and visualize yourself completing them successfully.",
        "Write about a positive affirmation you can repeat to yourself throughout the day.",
        "Describe the type of energy you want to bring into your interactions with others today.",
        "Reflect on a recent success or achievement and let it inspire you for the day ahead.",
        "Write a brief note of encouragement to yourself for any challenges you may face today.",
        "What can you do today to nourish your mind, body, or soul?",
        "List three things you're proud of from yesterday and use them to fuel your motivation for today.",
        "Reflect on a past mistake or setback and think about how you can approach similar situations differently today.",
        "Write down one thing you're excited to learn or explore today.",
        "Describe a goal you're working towards and identify one small step you can take today to move closer to it.",
        "Think about someone you care about and consider how you can make their day a little brighter.",
        "Write about a habit or routine you want to cultivate to enhance your productivity or well-being.",
        "Reflect on the value of self-care and identify one self-care practice you can incorporate into your day today.",
        "Write a brief gratitude list for the morning, focusing on what you appreciate about this moment.",
        "Describe how you want to show up for yourself and others today, and set an intention to embody that."
    ],
    "Night": [
        "Reflect on one thing you accomplished today that you're proud of.",
        "Write about a moment today that brought you joy or gratitude.",
        "List three things you're grateful for from today's experiences.",
        "Describe one challenge you faced today and how you dealt with it.",
        "Write down one thing you learned today, whether big or small.",
        "Reflect on any moments of kindness you witnessed or experienced today.",
        "Write about a decision you made today and how it contributed to your growth.",
        "Describe a moment today when you felt at peace or content.",
        "List three things you're looking forward to tomorrow.",
        "Write a letter to yourself, acknowledging and validating your efforts and experiences of the day.",
        "Reflect on any moments today where you felt proud of yourself for staying true to your values.",
        "Describe one thing you could have done differently today, and how you'll approach it next time.",
        "Write about a person you interacted with today and something positive you noticed about them.",
        "List three things you did today to take care of your well-being.",
        "Reflect on the highs and lows of the day, and how they contributed to your overall experience.",
        "Write about a moment today when you felt inspired or motivated.",
        "Describe how you felt at the beginning of the day compared to now. What changed?",
        "List any insights or realizations you had today.",
        "Write down any worries or concerns you have, and then release them, knowing you've done your best for today.",
        "Reflect on one thing you're grateful for about yourself and your journey."
    ],
    'ShadowWork': [
        "Reflect on a recurring negative pattern in your life. Where do you think it stems from?",
        "Write about a fear or insecurity that you've been avoiding. What triggers it, and how does it affect your life?",
        "Describe a situation where you felt intense anger or resentment. What was the underlying cause?",
        "Write about a past mistake or regret that still weighs on you. What can you learn from it?",
        "Reflect on a trait or behavior in others that triggers a strong reaction in you. Why do you think it bothers you?",
        "Describe a time when you felt ashamed or embarrassed. What beliefs about yourself were activated?",
        "Write about a part of yourself that you keep hidden from others. Why do you hide it, and what are you afraid of?",
        "Reflect on a relationship that ended badly. What role did you play in its downfall?",
        "Write about a childhood memory that still haunts you. How does it influence your present beliefs or behaviors?",
        "Describe a situation where you felt jealous or envious of someone else. What does it reveal about your own desires or insecurities?",
        "Reflect on a time when you betrayed someone's trust. What motivated your actions, and how do you feel about it now?",
        "Write about a secret you've been keeping from yourself or others. What are you afraid would happen if it came to light?",
        "Describe a situation where you felt powerless or victimized. How does it affect your sense of self-worth?",
        "Reflect on a toxic relationship or friendship from your past. What kept you in it, and what did you learn from it?",
        "Write about a belief or expectation that you inherited from your family or society. Does it still serve you?",
        "Describe a part of yourself that you judge or criticize harshly. What would it take to accept and integrate it?",
        "Reflect on a time when you sabotaged your own success or happiness. What underlying fears were at play?",
        "Write about a desire or craving that you're ashamed of. What does it reveal about your unmet needs or desires?",
        "Describe a fantasy or daydream that you're hesitant to explore. What does it say about your hidden desires or fears?",
        "Reflect on a time when you felt like an outsider or didn't belong. How does it shape your interactions with others?"
    ],
    "GoalSetting": [
        "What are three big goals you want to achieve in the next year?",
        "Write about why each of these goals is important to you.",
        "Break down each goal into smaller, actionable steps.",
        "Identify potential obstacles or challenges for each goal and brainstorm ways to overcome them.",
        "Reflect on past goals you've achieved and what strategies worked well for you.",
        "Write about one goal that scares you but excites you at the same time. Why does it evoke such strong emotions?",
        "Describe your ideal outcome for each goal. What does success look like?",
        "Consider any resources or support you may need to achieve your goals, and how you can access them.",
        "Write a letter to your future self, reflecting on how you've achieved your goals and the journey it took to get there.",
        "List three action steps you can take today to move closer to one of your goals.",
        "Reflect on any limiting beliefs or self-doubt that may be holding you back from pursuing your goals.",
        "Visualize yourself achieving your goals. How does it feel? What do you see, hear, and experience?",
        "Write about a time when you achieved a goal against all odds. What lessons can you apply to your current goals?",
        "Identify any habits or behaviors that may be hindering your progress towards your goals. How can you change them?",
        "Write down at least one way you can celebrate each milestone along the way to achieving your goals.",
        "Consider the impact your goals may have on other areas of your life, such as relationships, health, or finances.",
        "Reflect on whether your goals align with your values and priorities. Are there any adjustments you need to make?",
        "Write a mantra or affirmation related to each of your goals to keep you motivated and focused.",
        "Visualize yourself overcoming any setbacks or failures on the path to achieving your goals. How will you bounce back?",
        "Create a vision board or collage representing your goals and display it somewhere you'll see it daily for inspiration."
    ],
    "Relationship": [
        "Describe what makes a relationship meaningful to you.",
        "Reflect on the qualities you value most in a partner or friend. Why are these qualities important to you?",
        "Write about a past relationship that taught you valuable lessons about yourself or others.",
        "Describe your ideal relationship dynamic. How do you envision it?",
        "Reflect on a recent interaction with a loved one. What did you learn about yourself or the other person?",
        "Write about a challenge you've faced in a relationship and how you worked through it.",
        "Describe a small gesture of kindness or love you can do for someone special in your life today.",
        "Reflect on your communication style in relationships. Is there room for improvement?",
        "Write about a disagreement you've had with someone close to you. How did you resolve it?",
        "Describe a time when you felt deeply connected to someone. What contributed to that sense of connection?",
        "Reflect on your boundaries in relationships. Are they healthy and respected?",
        "Write a letter to a loved one expressing your appreciation and gratitude for them.",
        "Describe your ideal way of spending quality time with someone you care about.",
        "Reflect on the role forgiveness plays in your relationships. Is there anyone you need to forgive or seek forgiveness from?",
        "Write about a relationship that has changed you for the better. How have you grown as a result?",
        "Describe a trait or behavior in yourself that you think positively impacts your relationships.",
        "Reflect on a time when you felt supported by someone close to you. How did it make you feel?",
        "Write about a relationship goal you have for yourself. How do you plan to achieve it?",
        "Describe a person in your life who inspires you to be a better version of yourself.",
        "Reflect on your past relationships and identify any patterns or lessons you've learned from them."
    ],
    "SelfImprovement": [
        "What is one area of your life you would like to improve, and why?",
        "Reflect on a recent challenge you faced. How can you grow from this experience?",
        "Write about a skill or hobby you've always wanted to learn. What steps can you take to start learning it?",
        "Describe a limiting belief you have about yourself. How can you reframe it into a more empowering belief?",
        "Reflect on your daily habits. Which ones are helping you move closer to your goals, and which ones are holding you back?",
        "Write about a book or article that inspired you recently. What lessons did you take away from it?",
        "Describe a goal you've been procrastinating on. What small action can you take today to get started?",
        "Reflect on a past failure or mistake. What did you learn from it, and how can you use that knowledge to improve?",
        "Write about a role model or mentor who has influenced your personal growth. What qualities do you admire most about them?",
        "Describe your ideal version of yourself. What steps can you take to align your actions with this vision?",
        "Reflect on your strengths and weaknesses. How can you leverage your strengths to overcome your weaknesses?",
        "Write a letter to your future self, outlining the person you aspire to become and the steps you will take to get there.",
        "Describe a self-care practice that nourishes your mind, body, or soul. How can you prioritize this practice in your life?",
        "Reflect on your values and priorities. Are they reflected in your daily choices and actions?",
        "Write about a fear or insecurity that is holding you back from reaching your full potential. How can you overcome it?",
        "Describe a positive change you've made in your life recently. What motivated you to make this change?",
        "Reflect on a time when you stepped out of your comfort zone. How did it contribute to your personal growth?",
        "Write about a habit you want to cultivate or break. What strategies can you use to make this change stick?",
        "Describe a skill or talent you possess that you would like to further develop. What steps can you take to improve?",
        "Reflect on your relationships with others. How can you be a better friend, partner, or family member?"
    ]
}
